<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkehub/v1/configmanagement/configmanagement.proto

namespace Google\Cloud\GkeHub\ConfigManagement\V1;

/**
 * Configuration for Config Sync
 *
 * Generated from protobuf message <code>google.cloud.gkehub.configmanagement.v1.ConfigSync</code>
 */
class ConfigSync extends \Google\Protobuf\Internal\Message
{
}
