// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/foo/v1/bar.proto

package com.google.cloud.foo.v1;

/**
 * <pre>
 * Some sample class
 * </pre>
 *
 * Protobuf type {@code google.cloud.foo.v1.SomeMessage}
 */
public final class SomeMessage {}
