<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkehub/v1/feature.proto

namespace Google\Cloud\GkeHub\V1\FeatureState;

use UnexpectedValueException;

/**
 * Code represents a machine-readable, high-level status of the Feature.
 *
 * Protobuf type <code>google.cloud.gkehub.v1.FeatureState.Code</code>
 */
class Code
{
}
