<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkehub/v1/membership.proto

namespace Google\Cloud\GkeHub\V1;

/**
 * Authority encodes how Google will recognize identities from this Membership.
 * See the workload identity documentation for more details:
 * https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
 *
 * Generated from protobuf message <code>google.cloud.gkehub.v1.Authority</code>
 */
class Authority extends \Google\Protobuf\Internal\Message
{
}
