name: Renovate Bot Config Validation

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  config_validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Renovate and Config Validator
      run: |
        npm install -g npm@latest
        npm install --global renovate
        renovate-config-validator
